### ISSUE TITLE
crash on windows

### ISSUE THREAD

**Issue by citygenius** [raryelcostasouza/pyTranscriber#15]
hi, I clicked transcribe audio/generate subtitles  button  and got this error below,  then the window disappeared

C:\Program Files (x86)\pyTranscriber>pyTranscriber.exe
Traceback (most recent call last):
  File "pytranscriber\control\thread_exec_autosub.py", line 116, in run
  File "pytranscriber\control\thread_exec_autosub.py", line 105, in __loopSelectedFiles
  File "pytranscriber\control\thread_exec_autosub.py", line 63, in __runAutosubForMedia
  File "pytranscriber\control\ctr_autosub.py", line 143, in generate_subtitles
AttributeError: type object 'Ctr_Autosub' has no attribute 'pool'

**Comment by raryelcostasouza** [comment]
I will be checking that. Thanks for reporting!

**Comment by Ador-able** [comment]
I encountered similar problems
`C:\Program Files (x86)\pyTranscriber>pyTranscriber.exe
Traceback (most recent call last):
  File "pytranscriber\control\thread_exec_autosub.py", line 116, in run
  File "pytranscriber\control\thread_exec_autosub.py", line 105, in __loopSelectedFiles
  File "pytranscriber\control\thread_exec_autosub.py", line 63, in __runAutosubForMedia
  File "pytranscriber\control\ctr_autosub.py", line 107, in generate_subtitles
  File "multiprocessing\pool.py", line 868, in next
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x0000029B72C9C850>'. Reason: 'TypeError("cannot pickle 'zlib.Decompress' object")'
Process SpawnPoolWorker-11:
Traceback (most recent call last):
  File "multiprocessing\pool.py", line 131, in worker
  File "multiprocessing\queues.py", line 365, in put
  File "multiprocessing\connection.py", line 200, in send_bytes
  File "multiprocessing\connection.py", line 280, in _send_bytes
BrokenPipeError: [WinError 232] 管道正在被关闭。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "multiprocessing\pool.py", line 136, in worker
  File "multiprocessing\queues.py", line 365, in put
  File "multiprocessing\connection.py", line 200, in send_bytes
  File "multiprocessing\connection.py", line 280, in _send_bytes
BrokenPipeError: [WinError 232] 管道正在被关闭。
Process SpawnPoolWorker-19:
Traceback (most recent call last):
  File "multiprocessing\pool.py", line 131, in worker
  File "multiprocessing\queues.py", line 365, in put
  File "multiprocessing\connection.py", line 200, in send_bytes
  File "multiprocessing\connection.py", line 280, in _send_bytes
BrokenPipeError: [WinError 232] 管道正在被关闭。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "multiprocessing\pool.py", line 136, in worker
  File "multiprocessing\queues.py", line 365, in put
  File "multiprocessing\connection.py", line 200, in send_bytes
  File "multiprocessing\connection.py", line 280, in _send_bytes
BrokenPipeError: [WinError 232] 管道正在被关闭。`

**Comment by luckyfatpig** [comment]
same problem

**Comment by raryelcostasouza** [comment]
@citygenius Are you running Windows 11 or Windows 10?

**Comment by raryelcostasouza** [comment]
Hi All. Please try with version 1.9 just released today and see if it solves your issues. Thanks

**Comment by raryelcostasouza** [comment]
Hi @citygenius @Ador-able @luckyfatpig 
Please try with version 1.9 just released today and see if it solves your issues. Thanks

**Comment by xdiugang** [comment]
> 

Hi @raryelcostasouza, thanks for the wonderful product. 
I am facing the same issue, e.g. BrokenPipeError: [WinError 232]管道正在关闭。
Windows 11.
Version: 1.7 and 1.9.
China network and using VPN.
Test google connection successfully.
Step 2/2, wait for 5 to 10 minutes, the process crashes.

**Comment by raryelcostasouza** [comment]
Please retry on latest version and let us know if issue continues
