### ISSUE TITLE
Cannot run it

### ISSUE THREAD

**Issue by yypk** [raryelcostasouza/pyTranscriber#9]
When I click the "Generate Subtitles" botton, it can run step 1. However, the whole program disappeared when it is running step 2.

**Comment by raryelcostasouza** [comment]
Which OS are you running? 
Could you please try to run the program from command line and pasting the output you get here. 
Thanks!

**Comment by citygenius** [comment]
C:\Program Files (x86)\pyTranscriber>pyTranscriber.exe
Traceback (most recent call last):
  File "pytranscriber\control\thread_exec_autosub.py", line 116, in run
  File "pytranscriber\control\thread_exec_autosub.py", line 105, in __loopSelectedFiles
  File "pytranscriber\control\thread_exec_autosub.py", line 63, in __runAutosubForMedia
  File "pytranscriber\control\ctr_autosub.py", line 143, in generate_subtitles
AttributeError: type object 'Ctr_Autosub' has no attribute 'pool'
